easy_admin:
    site_name: ' Ardi '
    entities:

      Adherant:
        class: App\Entity\Adherant
        label: "Adherant"
        form:
          fields:
              - photo
              - {type: 'group' , icon: 'pencil', label: 'Basic Information', css_class: 'col-lg-7 ' }
              - nom
              - prenom
              - cin
              - fonction
              - lieu_travail
              - idAdhesion
              - {type: 'group', icon: 'th_list', label: 'Contact Information', css_class: 'col-lg-5 '}
              - tel
              - tel2
              - adresse
              - mail
        list:
          collapse_actions: true
          actions: ['show', 'edit' , 'delete' ]
          batch_actions: [ 'delete' ]


      Adhesion:
        class: App\Entity\Adhesion
        list:
          collapse_actions: true
          actions: ['show', 'edit' , 'delete' ]
          batch_actions: [ 'delete' ]



      Article:
        class: App\Entity\Article
      BureauDirecteur:
        class: App\Entity\BureauDirecteur
      Convention:
        class: App\Entity\Convention

        list:
          collapse_actions: true
          actions: ['show', 'edit' , 'delete' ]
          batch_actions: [ 'delete' ]



      User:
        class: App\Entity\User

      Evenement:
        class: App\Entity\Evenement
        list:
          collapse_actions: true
          actions: ['show', 'edit' , 'delete' ]
          batch_actions: [ 'delete' ]

      Sponsor:
        class: App\Entity\Sponsor
      Depences:
        class: App\Entity\Depences
      Revenu:
        class: App\Entity\Revenu




